function circFun = cFun(xVar,gamCoefs,aVar,bVar,const,k)

jP = myJacobiP(numel(xVar),numel(gamCoefs)-2,aVar,1-bVar,xVar);

circFun =  gamCoefs(1)*(weight(xVar,aVar,-bVar) - 2*aVar/(1+aVar-bVar).*weight(xVar,aVar-1,-bVar)) ...
    + gamCoefs(2)*(weight(xVar,aVar,1-bVar)- 4*aVar*(1-bVar)/(1+aVar-bVar)/(2+aVar-bVar).*weight(xVar,aVar-1,-bVar)) ...
    + sum(gamCoefs(3:end).'.*weight(xVar,aVar,1-bVar).*jP(:,2:end),2) ...
    + const*(weight(xVar,0,-bVar) - 2^(1-aVar)*beta(1-bVar,1)/beta(1-bVar,aVar).*weight(xVar,aVar-1,-bVar)) ...
    + exp(-1i*k)*weight(xVar,aVar-1,-bVar)./(2.^(aVar-bVar).*beta(1-bVar,aVar));

end